spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order
          filters:
            - AuthenticationFilter
        - id: identity-service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    enabled: true


management:
  zipkin:
    tracing:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0