spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/saivamsikaruturi/spring-cloud-config-server-newrepo/tree/main"
  profiles:
    active: native
server:
  port: 9016

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    enabled: true